### PR TITLE
Typing

### PR DESCRIPTION
**Pull request by gjohansson-ST**
Up to date typing

### CODE REVIEW

**Review by helto4real — APPROVED** [review]
Thanks

**Review by helto4real — CHANGES_REQUESTED** [review]
Fix merge and CI error please

**Comment by gjohansson-ST** [comment]
I didn't consider it's running python 3.8. 
You want to keep it on this version?

**Comment by helto4real** [comment]
This component is used by Home Assistant. Think 3.10 should be fine. If you want to change to that it is fine.

**Review by helto4real — APPROVED** [review]

**Pull request merged**
